export const columns = [
    {
        field: 'jobNumber',
        headerName: 'Job Number',
        type: 'string',
        width: 150,
        editable: true,
    },
    {
        field: 'clientName',
        headerName: 'Client Name',
        type: 'string',
        width: 150,
        editable: true,
    },
    {
        field: 'movingFrom',
        headerName: 'Moving From',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'movingTo',
        headerName: 'Moving To',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'stage',
        headerName: 'Stage',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'moveType',
        headerName: 'Move Type',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'leadPhone',
        headerName: 'Lead Phone',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'jobDate',
        headerName: 'Job Date',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'lastCommunication',
        headerName: 'Last Communication',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'compaigns',
        headerName: 'Compaigns',
        type: 'string',
        width: 110,
        editable: true,
    },
    {
        field: 'unread',
        headerName: 'Unread',
        description: 'This column has a value getter and is not sortable.',
        sortable: false,
        width: 160,
        valueGetter: (params) => `${params.row.unread || ''}`,
    },
];